version: '3'

services:
    db:
        image: postgres
        ports:
          - "5432:5432" 
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    django:
        build: 
          context: ./main
          dockerfile: Dockerfile
        volumes:
          - ./api:/app/main
        ports:
          - "8000:8000"
        depends_on:
          - db
    frontend:
        build: 
          context: ./frontend
          dockerfile: Dockerfile
        volumes:
          - ./frontend:/src/app
          - /src/app/node_modules
        ports: 
          - "3000:3000"
        depends_on: 
          - django